import SwiftUI

/// Email + OTP login / signup flow. The OTP is generated by the backend
/// and surfaced as a local notification — users can drop the code in
/// either by hand or by tapping the banner.
struct AuthView: View {
    enum Step { case email, code }

    @Environment(AppState.self) private var appState
    @Environment(\.dismiss) private var dismiss

    /// `nil` means the screen presents both Login and Signup pickers.
    var fixedMode: AuthService.Mode?

    /// Callback after a successful login/signup. Defaults to dismiss.
    var onAuthenticated: (() -> Void)?

    @State private var mode: AuthService.Mode = .login
    @State private var step: Step = .email
    @State private var email: String = ""
    @State private var displayName: String = ""
    @State private var code: String = ""
    @State private var isWorking: Bool = false
    @State private var error: String?
    @State private var info: String?
    @State private var revealedOTP: String?

    init(mode: AuthService.Mode? = nil, onAuthenticated: (() -> Void)? = nil) {
        self.fixedMode = mode
        self.onAuthenticated = onAuthenticated
        self._mode = State(initialValue: mode ?? .login)
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: RFSpacing.lg) {
                header

                if fixedMode == nil {
                    Picker("Mode", selection: $mode) {
                        Text("Log In").tag(AuthService.Mode.login)
                        Text("Sign Up").tag(AuthService.Mode.signup)
                    }
                    .pickerStyle(.segmented)
                    .onChange(of: mode) { _, _ in resetFlow() }
                }

                switch step {
                case .email: emailStep
                case .code: codeStep
                }

                if let error {
                    Text(error)
                        .font(.system(size: 12, weight: .semibold))
                        .foregroundStyle(.red)
                        .accessibilityIdentifier("auth_error")
                }
                if let info {
                    Text(info)
                        .font(.system(size: 12, weight: .semibold))
                        .foregroundStyle(.green)
                }
                if let revealedOTP {
                    VStack(alignment: .leading, spacing: 4) {
                        Text("OTP (also sent as a local notification)")
                            .font(.system(size: 10, weight: .black))
                            .tracking(1.5)
                            .foregroundStyle(RFColor.onSurfaceVariant.opacity(0.7))
                        Text(revealedOTP)
                            .font(.system(size: 28, weight: .black, design: .monospaced))
                            .foregroundStyle(RFColor.primary)
                            .accessibilityIdentifier("auth_revealed_otp")
                    }
                    .padding(RFSpacing.md)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .background(RFColor.primary.opacity(0.08), in: RoundedRectangle(cornerRadius: 16))
                }
            }
            .padding(RFSpacing.lg)
        }
        .background(RFColor.surface.ignoresSafeArea())
        .navigationTitle(fixedMode == nil ? "Account" : (mode == .signup ? "Sign Up" : "Log In"))
        #if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
        #endif
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: RFSpacing.sm) {
            Eyebrow(text: mode == .signup ? "Join The Grid" : "Welcome Back", color: RFColor.primary)
            Text(mode == .signup ? "Create your hunter ID" : "Authenticate to sync")
                .font(.system(size: 28, weight: .black))
                .foregroundStyle(RFColor.onSurface)
            Text(mode == .signup
                 ? "Enter your email — we'll generate a one-time code and deliver it as a local notification."
                 : "Enter your email to receive a one-time code via local notification.")
                .font(.rfBody())
                .foregroundStyle(RFColor.onSurfaceVariant.opacity(0.75))
        }
    }

    @ViewBuilder
    private var emailStep: some View {
        VStack(spacing: RFSpacing.md) {
            if mode == .signup {
                TextField("Display name", text: $displayName)
                    .textFieldStyle(.roundedBorder)
                    .textContentType(.name)
                    .accessibilityIdentifier("auth_display_name")
            }
            TextField("Email", text: $email)
                .textFieldStyle(.roundedBorder)
                .textContentType(.emailAddress)
                .keyboardType(.emailAddress)
                .textInputAutocapitalization(.never)
                .autocorrectionDisabled()
                .accessibilityIdentifier("auth_email")

            if isWorking {
                ProgressView()
            } else {
                RFPrimaryButton(
                    title: mode == .signup ? "Send Sign-Up Code" : "Send Login Code",
                    icon: "paperplane.fill",
                    action: { Task { await requestOTP() } }
                )
                .accessibilityIdentifier("auth_send_otp")
            }
        }
    }

    @ViewBuilder
    private var codeStep: some View {
        VStack(spacing: RFSpacing.md) {
            Text("Code sent to \(email).")
                .font(.system(size: 12, weight: .semibold))
                .foregroundStyle(RFColor.onSurfaceVariant)
                .frame(maxWidth: .infinity, alignment: .leading)

            TextField("6-digit code", text: $code)
                .textFieldStyle(.roundedBorder)
                .keyboardType(.numberPad)
                .textContentType(.oneTimeCode)
                .accessibilityIdentifier("auth_code")

            if isWorking {
                ProgressView()
            } else {
                RFPrimaryButton(
                    title: mode == .signup ? "Create Account" : "Log In",
                    icon: "checkmark.circle.fill",
                    action: { Task { await submit() } }
                )
                .accessibilityIdentifier("auth_submit")
            }

            Button("Resend code") {
                Task { await requestOTP() }
            }
            .font(.system(size: 12, weight: .black))
            .foregroundStyle(RFColor.primary)
        }
    }

    private func resetFlow() {
        step = .email
        code = ""
        error = nil
        info = nil
        revealedOTP = nil
    }

    private func requestOTP() async {
        error = nil
        info = nil
        revealedOTP = nil
        isWorking = true
        defer { isWorking = false }
        do {
            let issued = try await appState.auth.requestOTP(email: email, mode: mode)
            info = "Code sent. Check your notifications."
            revealedOTP = issued
            step = .code
        } catch {
            self.error = error.localizedDescription
        }
    }

    private func submit() async {
        error = nil
        info = nil
        isWorking = true
        defer { isWorking = false }
        do {
            switch mode {
            case .login:
                try await appState.auth.login(email: email, code: code)
            case .signup:
                try await appState.auth.signup(email: email, code: code, displayName: displayName)
            }
            await MainActor.run {
                if let cb = onAuthenticated { cb() } else { dismiss() }
            }
        } catch {
            self.error = error.localizedDescription
        }
    }
}

#Preview {
    NavigationStack {
        AuthView()
            .environment(AppState())
    }
}
